
USE demo_db;


-- 세션3 에서 수행

-- DDL 시도(ALGORITHM=COPY)
ALTER TABLE orders ADD COLUMN hold_lock_copy INT NOT NULL DEFAULT 1, ALGORITHM=COPY;

-- DDL 시도(ALGORITHM=INPLACE)
ALTER TABLE orders ADD COLUMN hold_lock_test2 INT NOT NULL DEFAULT 1, ALGORITHM=INPLACE, LOCK=NONE;

