
USE demo_db;


DROP TABLE IF EXISTS seq_1_to_1000;
DROP TABLE IF EXISTS seq_1_to_100000;
DROP TABLE IF EXISTS seq_1_to_1000000;

DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;


DROP DATABASE demo_db;

